### ISSUE TITLE
Shogi Bugs

### ISSUE THREAD

**Issue by msurur** [torresb24/AlphaRelease#13]
1. Shogi pieces can overlap at the same spot, but can only overlap if the dumb AI moves them so.
2.  Out of bounds tiles are displayed for legal move highlights.
3. Some pieces (like the arrow pieces) cannot move.
4. Once pieces get to the opposite side they cannot move. 

-Checkers Group

**Comment by knightedDragon** [comment]
All except last part fixed in branch (promotion necessary to completely solve point 4)

**Comment by Matttran7** [comment]
Promotion implemented
