### ISSUE TITLE
Beta - Quarto Team

### ISSUE THREAD

**Issue by nakakura24** [torresb24/AlphaRelease#15]
1. I am constantly being told that I lost the game when the game is still in progress.
2. Game randomly crashed towards the middle of the game. It seemed to be caused by capturing too many pieces, but I ended up playing a game where I captured every piece but the king. The problem is not quite apparent.
3. Wasn't able to promote the gold general in the last three rows. Is it not promotable, or is this a bug?
4. Is there such thing as "check" in Shogi? If so, there is no announcement that the king is in check, or the game does not prevent certain moves when in/or going into check.
5. Wasn't able to promote the king. Is it not promotable, or is this a bug?

**Comment by kellye24** [comment]
1-3 and 5 should be resolved now

**Comment by Matttran7** [comment]
check has been decided, it is not necessary to the overall functionality of the game.
