### ISSUE TITLE
Shogi Bugs (Team Checkers)

### ISSUE THREAD

**Issue by torresb24** [torresb24/AlphaRelease#16]
- Upon loading into a new game, it immediately predicts that the human player has lost (forcing a restart game)
- Pieces you own are still able to overlap with other pieces that you own
- Some pieces do not prompt a new move from the other player
- How do you promote?
- App crashes after it displays the "you lose" message/always displays you lost message
- Move highlights can still appear if it isn't your turn upon onTouch() (this soft locks the game)
- On the side display the player's turn never updates, it always stays as the foolish fool's turn

**Comment by Matttran7** [comment]
No longer predicts lost
no longer able to overlap pieces
- selected piece will appear in right string
App now asks for restart instead of closing on loss
Only visual aspect, does not affect game
Player's turn now updates
