### ISSUE TITLE
Crazy8 Team

### ISSUE THREAD

**Issue by torresb24** [torresb24/AlphaRelease#17]
- can't promote knight
- knight makes it to the other side and crashes (might be an issue with promotion)
- capturing a piece doesn't put it in jail
- same colored pieces are confusing (friendly suggestion), wait... only on one tablet
- says "you lost" all the time
- spam text freezes game

**Comment by Matttran7** [comment]
Can now promote knight
knight crashing fixed
graveyard implemented
pieces are flipped 180 degrees for opp turn
no longer has set text
fixed spam text
