### ISSUE TITLE
Uno Team

### ISSUE THREAD

**Issue by torresb24** [torresb24/AlphaRelease#18]
- [ ] No check/checkmate (or if there is, there's no indicator)
- [ ] Knight crashes the game when it reaches the enemy's side (If I have to guess, you're trying to access tiles above the board for possible move highlighting?? Null object reference?)
- [x] Player turn text doesn't update
- [x] Flip board 180deg when human player is player 2 maybe?
- [ ] Player names don't change when they're changed in the lobby

**Comment by Matttran7** [comment]
Checkmate message implemented
Fixed knight crashing 
Player text updates
- Not supposed to flip board
Player names now change
