### ISSUE TITLE
Chess Team

### ISSUE THREAD

**Issue by torresb24** [torresb24/AlphaRelease#19]
- Able to press promote on a promoted pawn which wastes a turn
- Promoted to a bishop and it crashed
- Graveyard isn't displayed

**Comment by knightedDragon** [comment]
Knight and bishop still crash when promoted, but other stuff solved

**Comment by Matttran7** [comment]
Bishop issue fixed 
Graveyard is displayed

**Comment by Matttran7** [comment]
promote is supposed to count as a move
